apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "petclinic.serviceAccountName" . }}
  labels:
    {{- include "petclinic.labels" . | nindent 4 }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
